// <auto-generated />
using BackGroundTaskCrawler.Infrastructures.Persistanse.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackGroundTaskCrawler.Infrastructures.Persistanse.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    [Migration("20230122212021_changedatatypes")]
    partial class changedatatypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackGroundTaskCrawler.Domains.Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Dimention")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProductId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
